### ISSUE TITLE
OneDrive Link to Data is Unavailable

### ISSUE THREAD

**Issue by Xiaoven** [lkpttxg/WhereCodeGenerationByLLM#6]
## Description
Hello,

I tried accessing the dataset through [the OneDrive link provided](https://1drv.ms/u/s!AoC1JXWLcNgVgWqwX_qKd4lXTFQ5), but encountered an error message stating, “Something went wrong.” 

<img width="223" alt="image" src="https://github.com/user-attachments/assets/db449ac3-5a9b-492a-905c-06ae8011f25d" />

To troubleshoot, I:
- Checked the service status on [Microsoft Service Status](https://portal.office.com/servicestatus), which showed everything was up and running.
  <img width="455" alt="image" src="https://github.com/user-attachments/assets/ef49fd40-f7bd-46a6-9017-2fdb2988791e" />
- Tried accessing the link on multiple browsers (Safari and Chrome).
- Cleared the cache and opened the link in private/incognito mode.

Unfortunately, the error persists despite these efforts.

Would it be possible to provide an alternative method to access the data, such as another cloud storage service?

**Comment by lkpttxg** [comment]
Sorry. I have updated the invalid data link. New OneDrive link: https://1drv.ms/f/c/15d8708b7525b580/QoC1JXWLcNgggBXjAAAAAAAAsF_6ineJV0xUOQ
